### ISSUE TITLE
Unable to run due. 

### ISSUE THREAD

**Issue by jp555soul** [lokwkin/chatgpt-slackbot-node#27]
Unable to run due to envs. 

- Are they in one file? 
- How exactly does the `START_MODE` work with 2 different options?
- Would you mind providing an example of how your `env` file is setup?

**Comment by szymon-mutuu** [comment]
shouldn't you run two instances + redis?

**Comment by jp555soul** [comment]
@szymon-mutuu Thanks! Going to fast
